### ISSUE TITLE
RayCast3D not colliding

### ISSUE THREAD

**Issue by eimfach** [rodmaureirac/godot-tactical-rpg#8]
I created my own arena shape, as in the docs and placed two pawns but their RayCast3D is not colliding with any tile. The tiles are there though ...
My shape is almost flat

**Comment by eimfach** [comment]
`$Tile.get_collider()` is returning `null`

**Comment by ramaureirac** [comment]
hi, can you share more details of your arena node pls ?

**Comment by eimfach** [comment]
I can give you a copy of my project ... https://we.tl/t-ltlVAhFAJM

**Comment by ramaureirac** [comment]
hi, after take a look at your scene i noticed that some blender tiles were not correctly centered [1] also there was a small "y" offset value for player node [2] so the pawn was being created under the map (so no tile to collide with) [3]. after do the adjustments your scene was working again [4]

[1] https://ibb.co/J3RcLHy
[2] https://ibb.co/gVjzfKB
[3] https://ibb.co/TLSpk5M
[4] https://ibb.co/qp6GbB3

link: https://we.tl/t-tDnwQIOeQA

please let me know if this solves your issue, thanks

**Comment by eimfach** [comment]
Thanks ! Okay interesting, fixed the y offset. Though I don't understand [1] How can I see which tile is not centered ?

**Comment by eimfach** [comment]
I did: Set Origin -> Origin to Geometry

That fixed it

**Comment by ramaureirac** [comment]
cool!, no sure if there is a quick way to know which tiles are not centered but it's always a good idea to apply origin to geometry to all tiles. going to close this issue. feel free to re-open if needed 😄
